### GET request to example server
GET http://localhost:8080


###

GET http://localhost:8080/api/v1/user-data


###

POST http://localhost:8080/api/v1/user-data
Content-Type: application/json

{


  "f_name": "Jeffery",
  "l_name": "James",
  "jobApplied": "Software Engineer",
  "applicationStatus": "Awaiting Interview",
  "companyName": "Apple Inc",
  "salaryOffered": 5500



}

###
POST http://localhost:8080/api/comments
Content-Type: application/json

{
    "username": "Skinnyman",
  "content": "Nice Tits!!"
}

###
GET http://localhost:8080/api/comments

###
POST http://localhost:8080/api/messages
Content-Type: application/json

{
  "sender": "Emmanuel",
  "receiver": "Project Manager",
  "content": "I'm tired of this project."
}

###
GET http://localhost:8080/api/messages/user/Project Manager




